package com.bitaspire.jdborm.schema;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

/**
 * Declarative definition of a database column used by {@link Schema}.
 * <p>
 * The definition stores a SQL type plus optional inline constraints. It keeps
 * the API database-agnostic by allowing raw SQL fragments such as default
 * expressions and check expressions where dialects differ.
 * </p>
 */
public final class ColumnDefinition {

    private final String name;
    private final String type;
    private final List<String> constraints = new ArrayList<>();

    /**
     * Creates a new column definition.
     *
     * @param name the database column name
     * @param type the SQL type or full type expression
     * @throws NullPointerException if {@code name} or {@code type} is {@code null}
     */
    public ColumnDefinition(String name, String type) {
        this.name = Objects.requireNonNull(name, "name");
        this.type = Objects.requireNonNull(type, "type");
    }

    /**
     * Returns the database column name.
     *
     * @return the column name
     */
    public String name() {
        return name;
    }

    /**
     * Returns the SQL type or full type expression for this column.
     *
     * @return the column type expression
     */
    public String type() {
        return type;
    }

    /**
     * Returns inline constraints in declaration order.
     *
     * @return an immutable list of inline constraint fragments
     */
    public List<String> constraints() {
        return Collections.unmodifiableList(constraints);
    }

    /**
     * Adds {@code NOT NULL} to this column.
     *
     * @return this column definition for chaining
     */
    public ColumnDefinition notNull() {
        constraints.add("NOT NULL");
        return this;
    }

    /**
     * Adds {@code PRIMARY KEY} to this column.
     *
     * @return this column definition for chaining
     */
    public ColumnDefinition primaryKey() {
        constraints.add("PRIMARY KEY");
        return this;
    }

    /**
     * Adds {@code UNIQUE} to this column.
     *
     * @return this column definition for chaining
     */
    public ColumnDefinition unique() {
        constraints.add("UNIQUE");
        return this;
    }

    /**
     * Adds {@code AUTO_INCREMENT} to this column.
     * <p>
     * This fragment is supported by MySQL and some compatible databases. For
     * standard SQL/HSQLDB/PostgreSQL-style identity columns, use
     * {@link #generatedByDefaultAsIdentity()} or a raw type expression.
     * </p>
     *
     * @return this column definition for chaining
     */
    public ColumnDefinition autoIncrement() {
        constraints.add("AUTO_INCREMENT");
        return this;
    }

    /**
     * Adds {@code GENERATED BY DEFAULT AS IDENTITY} to this column.
     *
     * @return this column definition for chaining
     */
    public ColumnDefinition generatedByDefaultAsIdentity() {
        constraints.add("GENERATED BY DEFAULT AS IDENTITY");
        return this;
    }

    /**
     * Adds a raw SQL default expression to this column.
     *
     * @param expression the SQL expression to use after {@code DEFAULT}
     * @return this column definition for chaining
     * @throws NullPointerException if {@code expression} is {@code null}
     */
    public ColumnDefinition defaultExpression(String expression) {
        constraints.add("DEFAULT " + Objects.requireNonNull(expression, "expression"));
        return this;
    }

    /**
     * Adds a database-native random UUID default expression for the given dialect.
     * <p>
     * This is intended for UUIDv4-style database-generated values. For UUIDv7,
     * generate the value in Java with {@link Uuids#timeOrderedV7()} and insert it
     * explicitly, because database-native UUIDv7 functions are not standardized.
     * </p>
     *
     * @param dialect database dialect used to choose the UUID SQL function
     * @return this column definition for chaining
     * @throws NullPointerException if {@code dialect} is {@code null}
     */
    public ColumnDefinition defaultUuid(UuidDialect dialect) {
        return defaultExpression(Uuids.defaultExpression(dialect));
    }

    /**
     * Adds a PostgreSQL {@code gen_random_uuid()} default expression.
     * <p>
     * PostgreSQL requires the {@code pgcrypto} extension to be enabled for this
     * function.
     * </p>
     *
     * @return this column definition for chaining
     */
    public ColumnDefinition defaultPostgresUuid() {
        return defaultUuid(UuidDialect.POSTGRES);
    }

    /**
     * Adds a foreign-key reference fragment to this column.
     *
     * @param reference the referenced table and columns, for example {@code "users(id)"}
     * @return this column definition for chaining
     * @throws NullPointerException if {@code reference} is {@code null}
     */
    public ColumnDefinition references(String reference) {
        constraints.add("REFERENCES " + Objects.requireNonNull(reference, "reference"));
        return this;
    }

    /**
     * Adds an inline {@code CHECK (...)} constraint to this column.
     *
     * @param expression the check expression without surrounding parentheses
     * @return this column definition for chaining
     * @throws NullPointerException if {@code expression} is {@code null}
     */
    public ColumnDefinition check(String expression) {
        constraints.add("CHECK (" + Objects.requireNonNull(expression, "expression") + ")");
        return this;
    }

    /**
     * Adds a raw inline constraint fragment to this column.
     *
     * @param constraint the raw SQL constraint fragment
     * @return this column definition for chaining
     * @throws NullPointerException if {@code constraint} is {@code null}
     */
    public ColumnDefinition constraint(String constraint) {
        constraints.add(Objects.requireNonNull(constraint, "constraint"));
        return this;
    }

    /**
     * Converts this column to a SQL fragment suitable for CREATE/ALTER TABLE.
     *
     * @return the column SQL fragment, including the column name
     */
    public String toSql() {
        if (constraints.isEmpty()) {
            return name + " " + type;
        }
        return name + " " + type + " " + String.join(" ", constraints);
    }
}
