package com.bitaspire.jdborm;

import com.bitaspire.jdborm.query.InsertQuery;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Integration tests verifying that {@link InsertQuery#executeBatch()} correctly
 * binds {@code null} parameter values on a real database (HSQLDB).
 */
class BatchInsertIntegrationTest {

    private JdbORM db;

    @BeforeEach
    void setUp() {
        db = JdbORM.connect("jdbc:hsqldb:mem:testdb" + System.nanoTime(), "SA", "");
        db.execute("CREATE TABLE users (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(100), email VARCHAR(255))");
    }

    @AfterEach
    void tearDown() {
        if (db != null) {
            db.close();
        }
    }

    @Test
    void executeBatchBindsNullValues() throws SQLException {
        InsertQuery q = db.insert("users");
        q.set("name", "Alice").set("email", (Object) null).addBatch();
        q.set("name", "Bob").set("email", "bob@example.com").addBatch();
        int[] counts = q.executeBatch();

        assertEquals(2, counts.length);
        assertEquals(1, counts[0]);
        assertEquals(1, counts[1]);

        List<Map<String, Object>> rows = db.select("name", "email")
                .from("users")
                .orderBy("id")
                .execute((rs, rowNum) -> {
                    Map<String, Object> map = new HashMap<>();
                    map.put("name", rs.getString("name"));
                    map.put("email", rs.getObject("email"));
                    return map;
                });

        assertEquals(2, rows.size());
        assertEquals("Alice", rows.get(0).get("name"));
        assertNull(rows.get(0).get("email"));
        assertEquals("Bob", rows.get(1).get("name"));
        assertEquals("bob@example.com", rows.get(1).get("email"));
    }
}
