package com.bitaspire.jdborm;

import com.bitaspire.jdborm.schema.Schema;
import com.bitaspire.jdborm.schema.SchemaPushResult;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Integration tests for declarative schema push against a real HSQLDB database.
 */
class SchemaPushIntegrationTest {

    private JdbORM db;

    @BeforeEach
    void setUp() {
        db = JdbORM.connect("jdbc:hsqldb:mem:schema_push_" + System.nanoTime(), "SA", "");
    }

    @AfterEach
    void tearDown() {
        if (db != null) {
            db.close();
        }
    }

    @Test
    void pushSchemaCreatesTablesAddsColumnsAndCreatesIndexes() {
        Schema initial = Schema.create()
                .table("users", table -> table
                        .column("id", "INTEGER", col -> col.generatedByDefaultAsIdentity().primaryKey())
                        .column("name", "VARCHAR(100)", col -> col.notNull()));

        SchemaPushResult firstPush = db.pushSchema(initial);

        assertTrue(firstPush.changed());
        assertEquals(List.of("CREATE TABLE users (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(100) NOT NULL)"),
                firstPush.executedSql());

        db.insert("users").set("name", "Alice").execute();

        Schema expanded = Schema.create()
                .table("users", table -> table
                        .column("id", "INTEGER", col -> col.generatedByDefaultAsIdentity().primaryKey())
                        .column("name", "VARCHAR(100)", col -> col.notNull())
                        .column("email", "VARCHAR(255)")
                        .index("idx_users_email", "email"));

        SchemaPushResult secondPush = db.pushSchema(expanded);

        assertTrue(secondPush.changed());
        assertEquals(List.of(
                "ALTER TABLE users ADD COLUMN email VARCHAR(255)",
                "CREATE INDEX idx_users_email ON users (email)"), secondPush.executedSql());

        db.update("users").set("email", "alice@example.com").execute();
        String email = db.select("email").from("users")
                .execute((rs, rowNum) -> rs.getString("email"))
                .get(0);
        assertEquals("alice@example.com", email);

        SchemaPushResult thirdPush = db.pushSchema(expanded);

        assertFalse(thirdPush.changed());
        assertEquals(0, thirdPush.statementsExecuted());
        assertTrue(thirdPush.executedSql().isEmpty());
    }
}
